# Generated by Django 5.2.5 on 2025-08-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='month',
            new_name='month_number',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='base',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='remaining',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='year',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='extra_holiday_per_month',
        ),
        migrations.AddField(
            model_name='parameter',
            name='extra_holiday_current_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parameter',
            name='extra_holiday_next_year',
            field=models.IntegerField(default=0),
        ),
    ]
