# Generated by Django 5.2.5 on 2025-08-25 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_reformat_holiday_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='month_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(1)]),
        ),
    ]
