# Generated by Django 5.2.5 on 2025-08-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_alter_holiday_month_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='extra_holiday_current_year',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='extra_holiday_next_year',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='holiday_per_month',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='start_holiday_amount',
            field=models.FloatField(default=0),
        ),
    ]
