# Generated by Django 5.2.5 on 2025-09-07 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0004_alter_parameter_extra_holiday_current_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='extra_holiday_month_accumulation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='month_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
    ]
